# Generated by Django 5.2.7 on 2026-04-05 13:46

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_email_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('unsubscribe_token', models.UUIDField(default=profiles.models.NewsletterSubscription.default_token, editable=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
