# Generated by Django 5.2.7 on 2026-03-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
